### PR TITLE
Add new weights for Lepton MVA

### PR DESCRIPTION
**Pull request by kskovpen**
This PR introduces new weights for updated Lepton MVA training. Some additional tuning of the existing flags in the code was done to allow for separate trainings in all years.

### CODE REVIEW

**Comment by tomcornelis** [comment]
The implementation looks good, the only minor point is that it still dependent on these very old effective areas which were used for relIso and miniIso in the previous lepton mva's. Even though it probably does not matter too much of the mva itself, it might be a good idea to finally get rid of these historic dependencies which caused already a lot of syncing problems in the past.

**Comment by kskovpen** [comment]
> The implementation looks good, the only minor point is that it still dependends on these very old effective areas which were used for relIso and miniIso in the previous lepton mva's. Even though it probably does not matter too much of the mva itself, it might be a good idea to finally get rid of these historic dependencies which caused already a lot of syncing problems in the past.

Will work on that in the forthcoming commits.

**Comment by kskovpen** [comment]
I have added a DB-based relIso variable for muons to be compatible with the NanoAOD format. Could you merge this PR? 

As for EA for electrons, I propose it to be a separate PR. We need to think how to approach this, since the CMSSW workflows are using the currently implemented EAs.

**Comment by tomcornelis** [comment]
Actually I could do the effective areas thing tomorrow morning, I have experience in disentangling them before (i.e. there's the relIso stored in the trees, and the relIso_ttH used for the leptonMva --> actually, you probably used the relIso variable for the training, right? Because relIso_ttH is not saved). I can do the same for miniIso, were the one with the most recent EAs is saved in the tuples, while I have other miniIso variations to support the older tZq and ttH leptonMva's.

**Comment by kskovpen** [comment]
Yes, I used _relIso in the training for both electrons and muons. This electron variable uses the same EAs as in official NanoAOD production, while for the muon variable it would be preferable to switch to the deltaBeta implementation. In any case, please keep the backward compatibility and do not remove any existing isolation-related variables, if possible.

**Pull request merged**
