### PR TITLE
Add missing triggers

### PR DESCRIPTION
**Pull request by kskovpen**
These triggers are needed for multilepton analysis. For the time being, these additional triggers are put into separate category in order not to affect other analyses.

### CODE REVIEW

**Comment by wverbeke** [comment]
Are these unprescaled, like "HLT_Ele27_eta2p1_WPLoose_Gsf" ?

**Comment by kskovpen** [comment]
The majority are not, some are.

**Comment by wverbeke** [comment]
But do you want to use prescaled triggers in an analysis? It will make it very hard to know the correct efficiencies, and to predict this in MC. Especially if a big cocktail of triggers is used.

**Comment by kskovpen** [comment]
Yes, I would like to use it anyway.

**Pull request merged**
